version: '3.10'

services:
  app:
    build: ./
    command: streamlit run app/main.py --server.port 8501
    volumes:
      - ./:/usr/src/app
    ports:
      - 8501:8501
    image: yourstreamlitapp:latest
